print('Исполнитель "Черепаха" (ч.1)')
print('Использование циклов for, вложенных циклов, функций')
print('Упражнение №13: смайлик')
import turtle
turtle.shape('turtle')
turtle.penup()
turtle.forward(115)
turtle.left(90)
turtle.pendown()
turtle.fillcolor('yellow')
turtle.begin_fill()
for i in range(360):
    turtle.forward(2)
    turtle.left(1)
turtle.end_fill()
turtle.penup()
turtle.goto(-57.5, 57.5)
turtle.forward(15)
turtle.left(90)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
for i in range(180):
    turtle.forward(0.5)
    turtle.left(2)
turtle.end_fill()
turtle.right(90)
turtle.penup()
turtle.goto(57.5, 57.5)
turtle.forward(15)
turtle.left(90)
turtle.pendown()
turtle.fillcolor('blue')
turtle.begin_fill()
for i in range(180):
    turtle.forward(0.5)
    turtle.left(2)
turtle.end_fill()
turtle.left(90)
turtle.penup()
turtle.goto(0, 20)
turtle.pendown()
turtle.width(10)
turtle.forward(40)
turtle.penup()
turtle.goto(57.5, -20)
turtle.pendown()
turtle.color('red')
turtle.width(10)
for i in range(180):
    turtle.forward(1)
    turtle.right(1)
print()
